/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-01 07:08:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class logout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/leeseonghyeon/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1685528762099L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" d\n");
      out.write(" \n");
      out.write(" <!DOCTYPE html>\n");
      out.write(" <html lang=\"kr\">\n");
      out.write(" <head>\n");
      out.write("     <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("     <meta charset=\"utf-8\">\n");
      out.write("     <title>SLiPP Java Web Programming</title>\n");
      out.write("     <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\n");
      out.write("     <link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("     <!--[if lt IE 9]>\n");
      out.write("     <script src=\"//html5shim.googlecode.com/svn/trunk/html5.js\"></script>\n");
      out.write("     <![endif]-->\n");
      out.write("     <link href=\"../css/styles.css\" rel=\"stylesheet\">\n");
      out.write(" </head>\n");
      out.write(" <body>\n");
      out.write(" <nav class=\"navbar navbar-fixed-top header\">\n");
      out.write("     <div class=\"col-md-12\">\n");
      out.write("         <div class=\"navbar-header\">\n");
      out.write("\n");
      out.write("             <a href=\"../index.html\" class=\"navbar-brand\">SLiPP</a>\n");
      out.write("             <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-collapse1\">\n");
      out.write("                 <i class=\"glyphicon glyphicon-search\"></i>\n");
      out.write("             </button>\n");
      out.write("\n");
      out.write("         </div>\n");
      out.write("         <div class=\"collapse navbar-collapse\" id=\"navbar-collapse1\">\n");
      out.write("             <form class=\"navbar-form pull-left\">\n");
      out.write("                 <div class=\"input-group\" style=\"max-width:470px;\">\n");
      out.write("                     <input type=\"text\" class=\"form-control\" placeholder=\"Search\" name=\"srch-term\" id=\"srch-term\">\n");
      out.write("                     <div class=\"input-group-btn\">\n");
      out.write("                         <button class=\"btn btn-default btn-primary\" type=\"submit\"><i class=\"glyphicon glyphicon-search\"></i></button>\n");
      out.write("                     </div>\n");
      out.write("                 </div>\n");
      out.write("             </form>\n");
      out.write("             <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                 <li>\n");
      out.write("                     <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"glyphicon glyphicon-bell\"></i></a>\n");
      out.write("                     <ul class=\"dropdown-menu\">\n");
      out.write("                         <li><a href=\"https://slipp.net\" target=\"_blank\">SLiPP</a></li>\n");
      out.write("                         <li><a href=\"https://facebook.com\" target=\"_blank\">Facebook</a></li>\n");
      out.write("                     </ul>\n");
      out.write("                 </li>\n");
      out.write("                 <li><a href=\"../user/list.html\"><i class=\"glyphicon glyphicon-user\"></i></a></li>\n");
      out.write("             </ul>\n");
      out.write("         </div>\n");
      out.write("     </div>\n");
      out.write(" </nav>\n");
      out.write(" <div class=\"navbar navbar-default\" id=\"subnav\">\n");
      out.write("     <div class=\"col-md-12\">\n");
      out.write("         <div class=\"navbar-header\">\n");
      out.write("             <a href=\"#\" style=\"margin-left:15px;\" class=\"navbar-btn btn btn-default btn-plus dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"glyphicon glyphicon-home\" style=\"color:#dd1111;\"></i> Home <small><i class=\"glyphicon glyphicon-chevron-down\"></i></small></a>\n");
      out.write("             <ul class=\"nav dropdown-menu\">\n");
      out.write("                 <li><a href=\"../user/profile.html\"><i class=\"glyphicon glyphicon-user\" style=\"color:#1111dd;\"></i> Profile</a></li>\n");
      out.write("                 <li class=\"nav-divider\"></li>\n");
      out.write("                 <li><a href=\"#\"><i class=\"glyphicon glyphicon-cog\" style=\"color:#dd1111;\"></i> Settings</a></li>\n");
      out.write("             </ul>\n");
      out.write("         </div>\n");
      out.write("         <div class=\"collapse navbar-collapse\" id=\"navbar-collapse2\">\n");
      out.write("             <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                 <li class=\"active\"><a href=\"../index.html\">Posts</a></li>\n");
      out.write("                         <li><a href=\"/user/logout.html\" role=\"button\">로그아웃</a></li>\n");
      out.write("                         <li><a href=\"/user/update\" role=\"button\">개인정보수정</a></li>\n");
      out.write("                         <li><a href=\"/user/login.html\" role=\"button\">로그인</a></li>\n");
      out.write("                         <li><a href=\"/user/form.html\" role=\"button\">회원가입</a></li>\n");
      out.write("             </ul>\n");
      out.write("         </div>\n");
      out.write("     </div>\n");
      out.write(" </div>\n");
      out.write("\n");
      out.write("<div class=\"container\" id=\"main\">\n");
      out.write("   <div class=\"col-md-12 col-sm-12 col-lg-10 col-lg-offset-1\">\n");
      out.write("      <div class=\"panel panel-default qna-list\">\n");
      out.write("          <ul class=\"list\">\n");
      out.write("              <li>\n");
      out.write("                  <div class=\"wrap\">\n");
      out.write("                      <div class=\"main\">\n");
      out.write("                          <strong class=\"subject\">\n");
      out.write("                              <a href=\"./qna/show.html\">국내에서 Ruby on Rails와 Play가 활성화되기 힘든 이유는 뭘까?</a>\n");
      out.write("                          </strong>\n");
      out.write("                          <div class=\"auth-info\">\n");
      out.write("                              <i class=\"icon-add-comment\"></i>\n");
      out.write("                              <span class=\"time\">2016-01-15 18:47</span>\n");
      out.write("                              <a href=\"./user/profile.html\" class=\"author\">자바지기</a>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"reply\" title=\"댓글\">\n");
      out.write("                              <i class=\"icon-reply\"></i>\n");
      out.write("                              <span class=\"point\">8</span>\n");
      out.write("                          </div>\n");
      out.write("                      </div>\n");
      out.write("                  </div>\n");
      out.write("              </li>\n");
      out.write("              <li>\n");
      out.write("                  <div class=\"wrap\">\n");
      out.write("                      <div class=\"main\">\n");
      out.write("                          <strong class=\"subject\">\n");
      out.write("                              <a href=\"./qna/show.html\">runtime 에 reflect 발동 주체 객체가 뭔지 알 방법이 있을까요?</a>\n");
      out.write("                          </strong>\n");
      out.write("                          <div class=\"auth-info\">\n");
      out.write("                              <i class=\"icon-add-comment\"></i>\n");
      out.write("                              <span class=\"time\">2016-01-05 18:47</span>\n");
      out.write("                              <a href=\"./user/profile.html\" class=\"author\">김문수</a>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"reply\" title=\"댓글\">\n");
      out.write("                              <i class=\"icon-reply\"></i>\n");
      out.write("                              <span class=\"point\">12</span>\n");
      out.write("                          </div>\n");
      out.write("                      </div>\n");
      out.write("                  </div>\n");
      out.write("              </li>\n");
      out.write("          </ul>\n");
      out.write("          <div class=\"row\">\n");
      out.write("              <div class=\"col-md-3\"></div>\n");
      out.write("              <div class=\"col-md-6 text-center\">\n");
      out.write("                  <ul class=\"pagination center-block\" style=\"display:inline-block;\">\n");
      out.write("                      <li><a href=\"#\">«</a></li>\n");
      out.write("                      <li><a href=\"#\">1</a></li>\n");
      out.write("                      <li><a href=\"#\">2</a></li>\n");
      out.write("                      <li><a href=\"#\">3</a></li>\n");
      out.write("                      <li><a href=\"#\">4</a></li>\n");
      out.write("                      <li><a href=\"#\">5</a></li>\n");
      out.write("                      <li><a href=\"#\">»</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-3 qna-write\">\n");
      out.write("                  <a href=\"./qna/form.html\" class=\"btn btn-primary pull-right\" role=\"button\">질문하기</a>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write(" <!-- script references -->\n");
      out.write(" <script src=\"../js/jquery-2.2.0.min.js\"></script>\n");
      out.write(" <script src=\"../js/bootstrap.min.js\"></script>\n");
      out.write(" <script src=\"../js/scripts.js\"></script>\n");
      out.write(" 	</body>\n");
      out.write(" </html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
